#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x89EFD588E975D6DF (rbtcollins@hp.com)
#
Name     : deprecated-testscenarios
Version  : 0.5.0
Release  : 43
URL      : https://pypi.python.org/packages/source/t/testscenarios/testscenarios-0.5.0.tar.gz
Source0  : https://pypi.python.org/packages/source/t/testscenarios/testscenarios-0.5.0.tar.gz
Source99 : https://pypi.python.org/packages/source/t/testscenarios/testscenarios-0.5.0.tar.gz.asc
Summary  : Testscenarios, a pyunit extension for dependency injection
Group    : Development/Tools
License  : Apache-2.0
Requires: deprecated-testscenarios-license = %{version}-%{release}
Requires: deprecated-testscenarios-python = %{version}-%{release}
Requires: pbr
Requires: testtools
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : deprecated-Babel-legacypython
BuildRequires : deprecated-pytz-legacypython
BuildRequires : extras
BuildRequires : pbr
BuildRequires : pbr-legacypython
BuildRequires : py
BuildRequires : pytest
BuildRequires : testtools
BuildRequires : traceback2

%description
*****************************************************************
testscenarios: extensions to python unittest to support scenarios
*****************************************************************

%package legacypython
Summary: legacypython components for the deprecated-testscenarios package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-testscenarios package.


%package license
Summary: license components for the deprecated-testscenarios package.
Group: Default

%description license
license components for the deprecated-testscenarios package.


%package python
Summary: python components for the deprecated-testscenarios package.
Group: Default

%description python
python components for the deprecated-testscenarios package.


%prep
%setup -q -n testscenarios-0.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554329236
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-testscenarios
cp Apache-2.0 %{buildroot}/usr/share/package-licenses/deprecated-testscenarios/Apache-2.0
cp COPYING %{buildroot}/usr/share/package-licenses/deprecated-testscenarios/COPYING
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-testscenarios/Apache-2.0
/usr/share/package-licenses/deprecated-testscenarios/COPYING

%files python
%defattr(-,root,root,-)
